### ISSUE TITLE
Tedd.KinectNetworkCamClient - SendThreadLoop

### ISSUE THREAD

**Issue by razier** [tedd/Tedd.VirtualNetworkCam#1]
So this isn't exactly an issue, but I am trying to convert an OpenCvSharp Mat to Bytes in order to send it to the virtual camera via _client.SendImage while looking at SendThreadLoop as an example;

But sadly I can't actually figure out on the buffer bytes shifting being done in backBufferSpan

Sending the frame directly by converting OpenCvSharp Mat e.g. _client.SendImage(frame.ToBytes()) doesn't seem to do anything,

While messing around with the OpenCvSharp Mat toBytes() into backBufferSpan gave me a weird colored lines in the virtual camera (so I am sure I would also need to shift some bytes somewhere to make this work).

Any hints or direction on what I should look into?

**Comment by tedd** [comment]
Hi

I'm not sure what format Mat is in.

The format sent in `_client.SendImage(backBuffer);` is raw RGB or RGBA. I'm doing a flip there due to image coming from Kinect is BGRA and virtual webcam in Windows wants it upside-down.

The dimensions of the image must match `_client.Height`, `_client.Width` and `_client.BytesPerPixel`. What actually happens is that the application using the webcam is negotiating to find a suitable format with the driver. The driver should then report back through network protocol preferred format. I'm not sure that part is working correctly as I've only tried this rewrite in 32-bit Zoom at 1920x1080 32-bit color. So maybe start with testing it in Zoom, just to see that it works there.

I would start with this:
* 32-bit Zoom client
* Compile driver to 32-bit
* Modify install.bat and uninstall.bat replace "Framework64" with "Framework"

I made a quick test now. This will load a PNG-image and send it as webcam image. Basically "var image" here replaces "var image" in SendThreadLoop() in MainWindow.xaml.cs. (This sample is not disposing bitmap etc here, this is just for demonstration.)

```
// Load PNG-image that is 1920x1080
var bitmapImage = new BitmapImage(new Uri(@"c:\temp\test.png"));
var writeableBitmap = new WriteableBitmap(bitmapImage);
// Set up a buffer to cache raw image in
var size = _bitmap.PixelWidth * _bitmap.PixelHeight * 4;
var pngImage = new Memory<byte>(new byte[size]);
// Copy the raw image into buffer
var span = new Span<byte>((void*)writeableBitmap.BackBuffer, size);
span.CopyTo(pngImage.Span);

// Inside for(;;) loop
var image = pngImage.Span;
// IWe do some conversion from image to backBuffer (BGRA->RGBA etc)
// Then we send it
_client.SendImage(backBuffer);
```

**Comment by razier** [comment]
Hi Tedd, thank you for replying!

With your reply I manage to figure out that my earlier Mat size was too small (640 x 480); I adjust my code and manage to get it to my max camera size (1280 x 720).

Mat type was CV_8UC3, which somehow translated to 8 bit 3 bytes per pixel (I suppose I should refer to the _client.BytesPerPixel and convert it accordingly via CvtColor)

_client.Width and _client.Height however is 1920 x 1080 (so I tried to resize my Mat to fit this)

Cv2.CvtColor(oriframe, oriframe, ColorConversionCodes.RGB2RGBA);
Cv2.Resize(oriframe, frame, new OpenCvSharp.Size(_client.Width, _client.Height));

byte[] backBuffer = null;
backBuffer = frame.ToBytes();

While I thought I had successfully do the conversion, I am still getting random black bar and static noise

<img width="524" alt="campreview" src="https://user-images.githubusercontent.com/1881987/82569386-bf0cea00-9bb2-11ea-880c-45ac01caea0b.png">

Possible for you to share your complete test code for the png test you did? I had tried to work it out on my own but not getting any output (just black screen) on the virtual camera even with a simple png.

**Comment by tedd** [comment]
I've refactored the client a bit to make it easier to test.

The colorful noise can be a result of random data put in when format is unknown, or it could be incorrect format sent (difficult to tell). I used the random noise to debug, see: https://github.com/tedd/Tedd.VirtualNetworkCam/blob/master/src/Tedd.KinectNetworkCamClient/ImageMixer.cs#L130

If you call the CamOnNewImage with your raw image data it should display in WPF app. https://github.com/tedd/Tedd.VirtualNetworkCam/blob/master/src/Tedd.KinectNetworkCamClient/MainWindow.xaml.cs#L81

I don't have time for more today, but I'll try to finish it tomorrow with loading of PNG background image as well. I switched from .Net's WriteableBitmap to a version I've made myself that gives fast multi-threaded access to memory, but I haven't ported all the load/save methods to it yet. (This one https://github.com/tedd/Tedd.WritableBitmap )

If I were to guess from the picture, you are not sending enough data.

I don't know if the screenshot is the full picture, but I'll measure based on that, The screenshot is approximately 1046x545=570 070 pixels. It seems to be resized a bit, and doesn't match any ratio (4:3, 16:9) so probably cropped.

The static noise part of the screen seems to be 327x623=203 721, around 35% of what is needed. Even if you sent 3 bytes when 4 bytes was expected this would not account for more than 67907/3*4=271 628 bytes, still only 47% of what is needed.

**Comment by razier** [comment]
Hi Tedd,

I made some progress (I would also like to apologize for not trying to understand your code better earlier).

I coded the following function to decode the jpg (I was looking at the bytes in particular to understand em, will look into Tedd.WritableBitmap later)

	private byte[] readImage2Bytes(string filename, int bytesPerPixel = 8)
	{
			Stream imageStreamSource = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read);
			JpegBitmapDecoder decoder = new JpegBitmapDecoder(imageStreamSource, BitmapCreateOptions.PreservePixelFormat, BitmapCacheOption.Default);
			BitmapSource bitmapSource = decoder.Frames[0];

			// Stride = (width) x (bytes per pixel)
			int stride = (int)bitmapSource.PixelWidth * (bitmapSource.Format.BitsPerPixel / bytesPerPixel);
			byte[] pixels = new byte[(int)bitmapSource.PixelHeight * stride];
	
			bitmapSource.CopyPixels(pixels, stride, 0);
			return pixels;		
	}

And then by looking at your code and trying to understand it better, I realized my mistake (for the image bit/bytes I was reading it at 4 bytes instead of 3; once I adjusted that it works like a charm!)

	image = readImage2Bytes("sky.jpg", 8);

	var iWidth = _client.Width;
	var iHeight = _client.Height;
	var dcl = backBufferSpan.Length - 1;
	for (var x = 0; x < iWidth; x++)
	{
		for (var y = 0; y < iHeight; y++)
		{
			//0,3,6,9,12 - 3 bytes per pixel (hardcoded 3 for testing, should refer to _client.BytesPerPixel)
			var bytepos = ((y * width) + x) * 3;
			//3 bytes per pixel
			var imagebitpos = ((y * width) + x) * 3;
	
			backBufferSpan[dcl - (bytepos + 0)] = image[imagebitpos + 2];
			backBufferSpan[dcl - (bytepos + 1)] = image[imagebitpos + 1];
			backBufferSpan[dcl - (bytepos + 2)] = image[imagebitpos + 0];
	
			if (y == 0)
			{
				Console.WriteLine(bytepos.ToString());
			}
		}
	}
	// Send backbuffer
	_client.SendImage(backBuffer);

<img width="525" alt="sampleoutput2" src="https://user-images.githubusercontent.com/1881987/82728506-29dd3300-9d23-11ea-8720-eea7dbdb97d8.png">

Thank you once again for replying, I appreciate the help!

p.s. To those who are stuck with the BGR / RGB on the image loaded, I basically just created a red image the size of the _camera.width and _camera.height then observe the bytes after loading the image to see the sequence (nearest byte value to 255 would be red).

**Comment by tedd** [comment]
That's great :)

I wrote the camera and network portion, but the sample client app was a mess (in part due to rewrite from Tasks and Pipelines that didn't work). Cleaned it up a bit now so hopefully it will be easier to understand.

The code is cleaner, but slightly less efficient. By my count the total from background+Kinect to app is doing 9 copies of image now all in all. Still very small latency, so it works fine.

**Comment by razier** [comment]
Hi Tedd,

Just wanted to share that I made a quick Python version of your Tedd.VirtualNetworkCamClient https://github.com/razier/TeddVirtualNetworkCamClient

Thank you once again for creating the VirtualNetworkCam! :)

**Comment by tedd** [comment]
That is cool. Thanks :)
